Feature/jitsi
TableCo/ios-sdk pull request #3
Opened 2020-11-17 12:07 UTC by AAfify1

Jitsi Implementation

2020-11-18 09:22 UTC, gazreese requested changes
Code looks great, but just need to address these before we squash and merge into master.

Might be worth copying-over the sample app as-is to the private repo so that we've got a way to get back to a testable version?

2020-11-18 09:22 UTC, gazreese commented on TableSDK/Table SDK/SDK/ViewControllers/JitsiVideo/JitsiVideoVC.swift
> +        let tokenizedURL = "https://8x8.vc/" + self.tenant + "/" + self.roomID + "?jwt=" + self.token
Is this URL going to be the same with dev / production? Do we need to double check with the Table team?

2020-11-18 09:25 UTC, AAfify1 commented on TableSDK/Podfile
> +post_install do |installer|
This was required for Jitsi in their documentation

2020-11-18 09:27 UTC, AAfify1 commented on SampleProject/TableSample/ViewController.swift
> +        Table.initialize(workspaceUrl: "https://develop3.dev.table.co", apiKey: "test_key", onSuccessInitializeCompletion: {
changed and pushed

2020-11-18 09:27 UTC, AAfify1 commented on SampleProject/TableSample/ViewController.swift
> +        userAttrib.firstName = "IOS"
changed and pushed

2020-11-30 09:08 UTC, gazreese approved these changes

2020-12-04 15:47 UTC, gazreese approved these changes

2020-12-07 09:01 UTC, merged